version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build: .
    command: python3 worker.py
    env_file:
      - .env
    environment:
      - REDISTOGO_URL=redis://redis@redis:6379
      - GOOGLE_CHROME_SHIM=/usr/bin/chromium
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - redis
  clock:
    build: .
    command: python3 clock.py
    env_file:
      - .env
    environment:
      - REDISTOGO_URL=redis://redis@redis:6379
      - GOOGLE_CHROME_SHIM=/usr/bin/chromium
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - redis
